---
apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: service.nodeport.global
spec:
  policy:
    kyverno:
      background: false
      rules:
        - exclude:
            resources: {}
          generate:
            clone: {}
            cloneList: {}
          match:
            resources:
              kinds:
                - Service
          mutate: {}
          name: validate-nodeport
          validate:
            message: Services of type NodePort are not allowed
            pattern:
              spec:
                =(type): "!NodePort"
      validationFailureAction: enforce
    type: Kyverno
  target:
    cluster: {}
    namespace: {}
