---
apiVersion: package.appvia.io/v2beta1
kind: Package
metadata:
  labels:
    packages.appvia.io/name: kube-downscaler
  name: kube-downscaler
spec:
  installNamespace: kube-downscaler
  name: kube-downscaler
  releaseName: kube-downscaler
  selectors:
    matchExpressions:
      - key: appvia.io/managementcluster
        operator: DoesNotExist
  source:
    helm:
      name: kube-downscaler
      url: https://charts.deliveryhero.io/
      version: v0.7.2
  summary: kube downscaler
  values: {}
  version: v0.7.2
