---
apiVersion: compute.appvia.io/v2beta1
kind: ClusterPlan
metadata:
  annotations:
    defaults.appvia.io/version: v2.4.5-1700584078
  name: gke-standard
spec:
  allocation:
    type: all
    workspaces:
      - "*"
  summary: General purpose GKE cluster.
  template:
    channel: default
    clusterLabels:
      appvia.io/ingresspublic: "true"
    enableAutoUpgrade: false
    enablePrivateCluster: false
    networking:
      authorizedMasterNetworks:
        - cidr: 0.0.0.0/0
          name: default
      authorizedNetworks:
        - cidr: 0.0.0.0/0
          name: default
      networkPlan: gke-standard
    nodePools:
      - autoscaling:
          enabled: true
          maxSize: 10
          minSize: 1
        diskSize: 30
        image: COS_CONTAINERD
        logicalName: compute
        machine: n2-standard-2
        maxPodsPerNode: 110
        size: 1
    provider: GKE
    providerDetails:
      gke:
        enableHTTPLoadBalancer: false
        enableHorizontalPodAutoscaler: true
        enableShieldedNodes: false
        enableStackDriverLogging: true
        enableStackDriverMetrics: true
        masterIPV4Cidr: 172.16.0.16/28
      type: GKE
    quotaLimits:
      default: small
      templates:
        - constraints:
            hardQuota:
              requests.cpu: "1"
              requests.memory: 3.5Gi
            limitRanges:
              - max:
                  cpu: 256m
                  ephemeral-storage: 1.875Gi
                  memory: 896Mi
                type: Pod
          name: small
          resourceDefaults:
            - default:
                cpu: 256m
                ephemeral-storage: 10Mi
                memory: 896Mi
              defaultRequest:
                cpu: 50m
                memory: 200Mi
              type: Container
        - constraints:
            hardQuota:
              requests.cpu: "2"
              requests.memory: 7Gi
            limitRanges:
              - max:
                  cpu: 512m
                  ephemeral-storage: 3.75Gi
                  memory: 1792Mi
                type: Pod
          name: medium
          resourceDefaults:
            - default:
                cpu: 512m
                ephemeral-storage: 500Mi
                memory: 1792Mi
              defaultRequest:
                cpu: 50m
                memory: 200Mi
              type: Container
        - constraints:
            hardQuota:
              requests.cpu: 14Gi
              requests.memory: 7Gi
            limitRanges:
              - max:
                  cpu: "1"
                  ephemeral-storage: 7.5Gi
                  memory: 3584Mi
                type: Pod
          name: large
          resourceDefaults:
            - default:
                cpu: "1"
                ephemeral-storage: 1Gi
                memory: 1792Mi
              defaultRequest:
                cpu: 50m
                memory: 200Mi
              type: Container
    region: europe-west2
    security:
      podSecurityStandard:
        allowed:
          - restricted
          - baseline
          - privileged
        defaultProfile: baseline
        enabled: true
